---
name: Practical Task
about: Template for a student practical task
title: "[Task] <Short Task Title>"
labels: task
assignees: ''

---

## Task Title
<!-- Provide the title of the task here -->

## Description
<!-- Give a detailed description of the task. Include context, objectives, and expected outcomes. -->

## Learning Objectives
<!-- List 2-5 learning objectives the student should achieve by completing this task -->

1. 
2. 
3. 

## Instructions
<!-- Step-by-step instructions for completing the task -->

1. 
2. 
3. 

## Requirements / Deliverables
<!-- Clearly state what students need to submit or demonstrate -->

- [ ] 
- [ ] 
- [ ] 

## Submission
<!-- Explain how students should submit: via pull request, attaching files, etc. -->

## Hints / Resources
<!-- Optional: provide links to resources, documentation, or tips -->

## Grading Criteria
<!-- Optional but useful: give a rubric for grading -->

| Criteria | Points |
|----------|--------|
| Correctness / Functionality |  |
| Code style / Documentation |  |
| Creativity / Extra effort |  |
| Timeliness |  |
