local_costmap:
  ros__parameters:
    update_frequency: 1.0
    resolution: 0.1
    obstacle_layer:
      obstacle_range: 3.0
      raytrace_range: 2.0
    rolling_window: true
    track_unknown_space: true
    transform_tolerance: 0.5
    subscribe_to_updates: false
    plugins:
    - obstacle_layer
    width: 3
    height: 2
    inflate_unknown: true
    inflate_around_unknown: true
