local_costmap:
  ros__parameters:
    update_frequency: 1.0
    resolution: 0.2
    obstacle_layer:
      obstacle_range: 1.0
      raytrace_range: 2.0
    rolling_window: false
    track_unknown_space: false
    transform_tolerance: 1.0
    subscribe_to_updates: true
    plugins:
    - obstacle_layer
    inflate_unknown: false
    inflate_around_unknown: false
