local_costmap:
  ros__parameters:
    update_frequency: 10.0
    resolution: 0.2
    rolling_window: false
    track_unknown_space: true
    transform_tolerance: 1.0
    subscribe_to_updates: false
    plugins:
    - voxel_layer
    voxel_layer:
      publish_voxel_map: true
      z_voxels: 15
      unknown_threshold: 15
      mark_threshold: 2
    inflate_unknown: true
    inflate_around_unknown: false
