local_costmap:
  ros__parameters:
    update_frequency: 5.0
    resolution: 0.2
    rolling_window: true
    track_unknown_space: true
    transform_tolerance: 0.1
    subscribe_to_updates: false
    plugins: []
    width: 3
    height: 1
    inflate_unknown: true
    inflate_around_unknown: false
