local_costmap:
  ros__parameters:
    update_frequency: 5.0
    resolution: 0.1
    rolling_window: true
    track_unknown_space: false
    transform_tolerance: 1.0
    subscribe_to_updates: true
    plugins:
    - voxel_layer
    width: 3
    height: 1
    inflate_unknown: false
    inflate_around_unknown: false
    voxel_layer:
      publish_voxel_map: false
      unknown_threshold: 5
      mark_threshold: 2
