local_costmap:
  ros__parameters:
    update_frequency: 10.0
    resolution: 0.1
    obstacle_layer:
      obstacle_range: 2.0
      raytrace_range: 3.0
    rolling_window: true
    track_unknown_space: false
    transform_tolerance: 0.1
    subscribe_to_updates: true
    plugins:
    - obstacle_layer
    width: 2
    height: 3
    inflate_unknown: false
    inflate_around_unknown: false
