local_costmap:
  ros__parameters:
    update_frequency: 10.0
    resolution: 0.1
    rolling_window: true
    track_unknown_space: true
    transform_tolerance: 0.1
    subscribe_to_updates: false
    plugins: []
    width: 1
    height: 2
    inflate_unknown: true
    inflate_around_unknown: false
