local_costmap:
  ros__parameters:
    update_frequency: 1.0
    resolution: 0.2
    rolling_window: false
    track_unknown_space: true
    transform_tolerance: 1.0
    subscribe_to_updates: false
    plugins: []
    inflate_unknown: true
    inflate_around_unknown: false
