local_costmap:
  ros__parameters:
    update_frequency: 5.0
    resolution: 0.2
    rolling_window: false
    track_unknown_space: false
    transform_tolerance: 0.5
    subscribe_to_updates: false
    plugins: []
    inflate_unknown: false
    inflate_around_unknown: false
