local_costmap:
  ros__parameters:
    update_frequency: 5.0
    resolution: 0.2
    obstacle_layer:
      obstacle_range: 1.0
      raytrace_range: 3.0
    rolling_window: true
    track_unknown_space: true
    transform_tolerance: 1.0
    subscribe_to_updates: true
    plugins:
    - obstacle_layer
    width: 3
    height: 2
    inflate_unknown: true
    inflate_around_unknown: false
