local_costmap:
  ros__parameters:
    update_frequency: 1.0
    resolution: 0.2
    rolling_window: true
    track_unknown_space: true
    transform_tolerance: 0.5
    subscribe_to_updates: true
    plugins:
    - voxel_layer
    width: 1
    height: 1
    voxel_layer:
      publish_voxel_map: true
      z_voxels: 10
      unknown_threshold: 5
      mark_threshold: 1
    inflate_unknown: true
    inflate_around_unknown: false
