global_costmap:
  global_costmap:
    ros__parameters:
      update_frequency: 10.0 #
      publish_frequency: 1.0
      global_frame: map
      robot_base_frame: base_link
      use_sim_time: True
      robot_radius: 0.22
      resolution: 0.2 #
      transform_tolerance: 1.0 #
      track_unknown_space: true # false
      inflate_unknknown: true # false
      plugins: ["static_layer"]
      static_layer:
        plugin: "nav2_costmap_2d::StaticLayer"
        enabled: true
        map_subscribe_transient_local: True
        subscribe_to_updates: True #
      always_send_full_costmap: False

# /global_costmap/global_costmap:
#   ros__parameters:
#     update_frequency: 1.0
#     resolution: 0.2
#     rolling_window: false
#     transform_tolerance: 1.0
#     subscribe_to_updates: false
#     track_unknown_space: false
#     inflate_unknknown: false
#     inflate_around_unknown: false
#     plugins:
#     - static_layer
#     - inflation_layer
#     inflation_layer:
#       plugin: nav2_costmap_2d::InflationLayer
#       enabled: true
#       inflation_radius: 0.75
#       cost_scaling_factor: 1.0
#       inflate_unknown: false
#       inflate_around_unknown: false
#     static_layer:
#       plugin: nav2_costmap_2d::StaticLayer
#       enabled: true
#       subscribe_to_updates: false
