global_costmap:
  global_costmap:
    ros__parameters:
      update_frequency: 10.0 #
      publish_frequency: 1.0
      global_frame: map
      robot_base_frame: base_link
      use_sim_time: True
      robot_radius: 0.22
      resolution: 0.2 #
      transform_tolerance: 0.1 #
      track_unknown_space: True # false
      plugins: ["static_layer", "inflation_layer"]
      static_layer:
        plugin: "nav2_costmap_2d::StaticLayer"
        enabled: true
        map_subscribe_transient_local: True
        subscribe_to_updates: True #
      inflation_layer:
        plugin: "nav2_costmap_2d::InflationLayer"
        cost_scaling_factor: 2.0 #
        inflation_radius: 0.5 #
        inflate_unknown: True #
        inflate_around_unknown: False # 
      always_send_full_costmap: True
