global_costmap:
  global_costmap:
    ros__parameters:
      update_frequency: 10.0 #
      publish_frequency: 1.0
      global_frame: map
      robot_base_frame: base_link
      use_sim_time: True
      robot_radius: 0.22
      resolution: 0.2 #
      transform_tolerance: 1.0 #
      track_unknown_space: True # false
      plugins: ["static_layer", "obstacle_layer", "inflation_layer"]
      obstacle_layer:
        plugin: "nav2_costmap_2d::ObstacleLayer"
        enabled: True
        observation_sources: scan
        scan:
          topic: /scan
          max_obstacle_height: 2.0
          clearing: True
          marking: True
          data_type: "LaserScan"
          raytrace_max_range: 1.0 #
          raytrace_min_range: 0.0
          obstacle_max_range: 2.0 #
          obstacle_min_range: 0.0
      static_layer:
        plugin: "nav2_costmap_2d::StaticLayer"
        enabled: true
        map_subscribe_transient_local: True
        subscribe_to_updates: True #
      inflation_layer:
        plugin: "nav2_costmap_2d::InflationLayer"
        cost_scaling_factor: 1.0 #
        inflation_radius: 0.75 #
        inflate_unknown: True #
        inflate_around_unknown: False # 
      always_send_full_costmap: True