global_costmap:
  global_costmap:
    ros__parameters:
      update_frequency: 1.0 #
      publish_frequency: 1.0
      global_frame: map
      robot_base_frame: base_link
      use_sim_time: True
      robot_radius: 0.22
      resolution: 0.1 #
      transform_tolerance: 0.1 #
      track_unknown_space: true # false
      inflate_unknknown: true # false
      plugins: ["static_layer", "obstacle_layer", "inflation_layer"]
      obstacle_layer:
        plugin: "nav2_costmap_2d::ObstacleLayer"
        enabled: True
        observation_sources: scan
        scan:
          topic: /scan
          max_obstacle_height: 2.0
          clearing: True
          marking: True
          data_type: "LaserScan"
          raytrace_max_range: 1.0 #
          raytrace_min_range: 0.0
          obstacle_max_range: 2.0 #
          obstacle_min_range: 0.0
      static_layer:
        plugin: "nav2_costmap_2d::StaticLayer"
        enabled: true
        map_subscribe_transient_local: True
        subscribe_to_updates: False ##
      inflation_layer:
        plugin: "nav2_costmap_2d::InflationLayer"
        cost_scaling_factor: 1.0 #
        inflation_radius: 0.35 #
        inflate_unknown: True #
        inflate_around_unknown: True # 
      always_send_full_costmap: True # 

# /global_costmap/global_costmap:
#   ros__parameters:
#     update_frequency: 1.0
#     resolution: 0.1
#     rolling_window: false
#     transform_tolerance: 0.1
#     subscribe_to_updates: false
#     track_unknown_space: false
#     inflate_unknknown: false
#     inflate_around_unknown: false
#     plugins:
#     - static_layer
#     - obstacle_layer
#     - inflation_layer
#     width: 1
#     height: 1
#     obstacle_layer:
#       plugin: nav2_costmap_2d::ObstacleLayer
#       enabled: true
#       observation_sources: scan
#       scan:
#         data_type: LaserScan
#         topic: /scan
#         marking: true
#         clearing: true
#         obstacle_max_range: 1.0
#         raytrace_max_range: 1.0
#     inflation_layer:
#       plugin: nav2_costmap_2d::InflationLayer
#       enabled: true
#       inflation_radius: 0.25
#       cost_scaling_factor: 1.0
#       inflate_unknown: false
#       inflate_around_unknown: false
#     static_layer:
#       plugin: nav2_costmap_2d::StaticLayer
#       enabled: true
#       subscribe_to_updates: false
