/global_costmap/global_costmap:
  ros__parameters:
    always_send_full_costmap: true
    clearable_layers: "['obstacle_layer', 'voxel_layer', 'range_layer']"
    filters: "[]"
    footprint: "[]"
    footprint_padding: 0.009999999776482582
    global_frame: "map"
    lethal_cost_threshold: 100
    map_topic: "/map"
    origin_x: 0.0
    origin_y: 0.0
    inflation_layer:
      cost_scaling_factor: 3.0
      enabled: true
      inflate_around_unknown: true
      inflate_unknown: true
      inflation_radius: 0.5
      plugin: "nav2_costmap_2d::InflationLayer"
    obstacle_layer:
      enabled: false
    voxel_layer:
      enabled: false
    static_layer:
      enabled: true
      map_subscribe_transient_local: true
      plugin: "nav2_costmap_2d::StaticLayer"
      subscribe_to_updates: false
      transform_tolerance: 0.0
    plugins: "['static_layer','inflation_layer']"
    publish_frequency: 0.5
    resolution: 0.1
    robot_base_frame: "base_link"
    robot_radius: 0.22
    track_unknown_space: true
    transform_tolerance: 0.5
    trinary_costmap: true
    unknown_cost_value: 255
    update_frequency: 0.5
    use_maximum: false
    use_sim_time: false
    width: 5
    height: 5
    