/local_costmap/local_costmap:
  ros__parameters:
    always_send_full_costmap: true
    clearable_layers: "['obstacle_layer','voxel_layer','range_layer']"
    filters: "[]"
    footprint: '[]'
    footprint_padding: 0.009999999776482582
    global_frame: "odom"
    height: 2
    inflation_layer:
      cost_scaling_factor: 2.0
      enabled: true
      inflate_around_unknown: false
      inflate_unknown: true
      inflation_radius: 0.75
      plugin: "nav2_costmap_2d::InflationLayer"
    lethal_cost_threshold: 100
    map_topic: "/map"
    origin_x: 0.0
    origin_y: 0.0
    plugins: "[]"
    publish_frequency: 2.0
    resolution: 0.2
    robot_base_frame: "base_link"
    robot_radius: 0.22
    rolling_window: false
    transform_tolerance: 1.0
    trinary_costmap: true
    unknown_cost_value: 255
    update_frequency: 1.0
    use_maximum: false
    use_sim_time: false
    voxel_layer:
      enabled: false
    obstacle_layer:
      enabled: false
    inflation_layer:
      enabled: false
    width: 2
    