local_costmap:
  local_costmap:
    ros__parameters:
      update_frequency: 10.0 #
      publish_frequency: 2.0
      global_frame: odom
      robot_base_frame: base_link
      use_sim_time: True
      rolling_window: True # Always True (otherwise the robot stucks)
      width: 2 #
      height: 2 #
      resolution: 0.2 #
      robot_radius: 0.22 # 
      track_unknown_space: true #
      plugins: ["voxel_layer"]
      # inflation_layer:
      #   plugin: "nav2_costmap_2d::InflationLayer"
      #   cost_scaling_factor: 3.0 #
      #   inflation_radius: 0.55 #
      #   inflate_unknown: True #
      #   inflate_around_unknown: False # 
      voxel_layer:
        plugin: "nav2_costmap_2d::VoxelLayer"
        enabled: true
        z_voxels: 15 #
        unknown_threshold: 15 #
        mark_threshold: 2 #
        publish_voxel_map: True #
        origin_z: 0.0
        z_resolution: 0.05
        max_obstacle_height: 2.0
        mark_threshold: 0
        # observation_sources: depth_camera_scan #
        # depth_camera_scan:
        #     topic: /intel_realsense_r200_depth/points  # Adjust with your depth camera's point cloud topic
        #     data_type: "PointCloud2"
        #     clearing: true
        #     marking: true
        #     max_obstacle_height: 2.0
        #     raytrace_max_range: 3.0
        #     raytrace_min_range: 0.0
        #     obstacle_max_range: 2.5
        #     obstacle_min_range: 0.0
        observation_sources: scan
        scan:
          topic: /scan
          max_obstacle_height: 2.0
          clearing: True
          marking: True
          data_type: "LaserScan"
          raytrace_max_range: 3.0
          raytrace_min_range: 0.0
          obstacle_max_range: 2.5
          obstacle_min_range: 0.0
      # static_layer:
      #   plugin: "nav2_costmap_2d::StaticLayer"
      #   map_subscribe_transient_local: True
      #   transform_tolerance: 1.0 #
      #   subscribe_to_updates: false #
      always_send_full_costmap: True
