local_costmap:
  local_costmap:
    ros__parameters:
      update_frequency: 5.0 #
      publish_frequency: 2.0
      global_frame: odom
      robot_base_frame: base_link
      use_sim_time: True
      rolling_window: True # Always True (otherwise the robot stucks)
      width: 1 #
      height: 1 #
      resolution: 0.2 #
      robot_radius: 0.22 # 
      track_unknown_space: True #
      plugins: ["voxel_layer"]
      voxel_layer:
        plugin: "nav2_costmap_2d::VoxelLayer"
        enabled: true
        z_voxels: 10 #
        unknown_threshold: 15 #
        mark_threshold: 2  #
        publish_voxel_map: True #
        origin_z: 0.0
        z_resolution: 0.05
        max_obstacle_height: 2.0
        mark_threshold: 0
        observation_sources: scan
        scan:
          topic: /scan
          max_obstacle_height: 2.0
          clearing: True
          marking: True
          data_type: "LaserScan"
          raytrace_max_range: 2.0 #
          raytrace_min_range: 0.0
          obstacle_max_range: 1.0 #
          obstacle_min_range: 0.0
      always_send_full_costmap: True