local_costmap:
  local_costmap:
    ros__parameters:
      update_frequency: 10.0
      publish_frequency: 2.0
      global_frame: odom
      robot_base_frame: base_link
      use_sim_time: true
      rolling_window: false
      resolution: 0.2
      transform_tolerance: 1.0
      subscribe_to_updates: false
      track_unknown_space: false
      inflate_unknknown: false
      inflate_around_unknown: false
      plugins: [ 'voxel_layer', 'inflation_layer' ]
      inflation_layer:
        plugin: "nav2_costmap_2d::InflationLayer"
        cost_scaling_factor: 3.0
        inflation_radius: 0.55
      voxel_layer:
        plugin: 'nav2_costmap_2d::VoxelLayer'
        enabled: true
        z_voxels: 15
        publish_voxel_map: false
        unknown_threshold: 15
        mark_threshold: 2
