local_costmap:
  local_costmap:
    ros__parameters:
      update_frequency: 5.0 #
      publish_frequency: 2.0
      global_frame: odom
      robot_base_frame: base_link
      use_sim_time: True
      rolling_window: True # Always True (otherwise the robot stucks)
      width: 3 #
      height: 1 #
      resolution: 0.1 #
      robot_radius: 0.22 # 
      track_unknown_space: False #
      plugins: ["voxel_layer"]
      voxel_layer:
        plugin: "nav2_costmap_2d::VoxelLayer"
        enabled: true
        z_voxels: 5 #
        unknown_threshold: 5 #
        mark_threshold: 2  #
        publish_voxel_map: False #
        origin_z: 0.0
        z_resolution: 0.05
        max_obstacle_height: 2.0
        observation_sources: depth_points

        depth_points:
          topic: /camera/depth/color/points     # <-- change to your point cloud topic
          data_type: PointCloud2
          marking: true
          clearing: true
          expected_update_rate: 0.0       # 0.0 = don’t timeout; set (e.g., 5.0) to require regular updates
          min_obstacle_height: 0.02       # filter ground/floor points (tweak as needed)
          max_obstacle_height: 2.0
          raytrace_max_range: 1.0 #
          obstacle_max_range: 3.0 #
          obstacle_min_range: 0.0
        # observation_sources: scan
        # scan:
        #   topic: /scan
        #   max_obstacle_height: 2.0
        #   clearing: True
        #   marking: True
        #   data_type: "LaserScan"
        #   raytrace_max_range: 1.0 #
        #   raytrace_min_range: 0.0
        #   obstacle_max_range: 3.0 #
        #   obstacle_min_range: 0.0
      always_send_full_costmap: True
