local_costmap:
  local_costmap:
    ros__parameters:
      update_frequency: 5.0
      publish_frequency: 2.0
      global_frame: odom
      robot_base_frame: base_link
      use_sim_time: true
      rolling_window: false
      resolution: 0.2
      transform_tolerance: 0.1
      subscribe_to_updates: false
      track_unknown_space: false
      inflate_unknknown: false
      inflate_around_unknown: false
      plugins: []
      width: 3
      height: 1
