/local_costmap/local_costmap:
  ros__parameters:
    always_send_full_costmap: true
    clearable_layers: "['obstacle_layer','voxel_layer','range_layer']"
    filters: "[]"
    footprint: "[]"
    footprint_padding: 0.009999999776482582
    global_frame: odom
    height: 3
    lethal_cost_threshold: 100
    map_topic: "/map"
    origin_x: 0.0
    origin_y: 0.0
    plugins: "['voxel_layer']"
    publish_frequency: 2.0
    resolution: 0.2
    robot_base_frame: "base_link"
    robot_radius: 0.22
    rolling_window: false
    transform_tolerance: 1.0
    trinary_costmap: true
    unknown_cost_value: 255
    update_frequency: 10.0
    use_maximum: false
    use_sim_time: false
    voxel_layer:
      combination_method: 1
      enabled: true
      footprint_clearing_enabled: true
      mark_threshold: 2
      max_obstacle_height: 2.0
      min_obstacle_height: 0.0
      observation_sources: "scan"
      origin_z: 0.0
      plugin: "nav2_costmap_2d::VoxelLayer"
      publish_voxel_map: true
      scan:
        clearing: true
        data_type: "LaserScan"
        expected_update_rate: 0.0
        inf_is_valid: false
        marking: true
        max_obstacle_height: 2.0
        min_obstacle_height: 0.0
        observation_persistence: 0.0
        obstacle_max_range: 3.0
        obstacle_min_range: 0.0
        raytrace_max_range: 3.0
        raytrace_min_range: 0.0
        topic: "/scan"
      unknown_threshold: 15
      z_resolution: 0.05
      z_voxels: 15
    observation_layer:
      enabled: false
    inflation_layer:
      enabled: false
    width: 3
    