global_costmap:
  ros__parameters:
    update_frequency: 5.0
    resolution: 0.2
    obstacle_layer:
      obstacle_range: 2.0
      raytrace_range: 2.0
    inflation_layer:
      inflation_radius: 0.5
      cost_scaling_factor: 2.0
    rolling_window: false
    track_unknown_space: false
    transform_tolerance: 0.5
    subscribe_to_updates: false
    plugins:
    - static_layer
    - obstacle_layer
    - inflation_layer
    inflate_unknown: false
    inflate_around_unknown: false
