global_costmap:
  ros__parameters:
    update_frequency: 1.0
    resolution: 0.2
    inflation_layer:
      inflation_radius: 0.75
      cost_scaling_factor: 1.0
    rolling_window: false
    track_unknown_space: false
    transform_tolerance: 1.0
    subscribe_to_updates: true
    plugins:
    - static_layer
    - inflation_layer
    inflate_unknown: false
    inflate_around_unknown: false
