global_costmap:
  ros__parameters:
    update_frequency: 10.0
    resolution: 0.2
    obstacle_layer:
      obstacle_range: 3.0
      raytrace_range: 3.0
    inflation_layer:
      inflation_radius: 0.75
      cost_scaling_factor: 3.0
    rolling_window: false
    track_unknown_space: true
    transform_tolerance: 1.0
    subscribe_to_updates: false
    plugins:
    - static_layer
    - obstacle_layer
    - inflation_layer
    inflate_unknown: true
    inflate_around_unknown: false
