global_costmap:
  ros__parameters:
    update_frequency: 5.0
    resolution: 0.2
    inflation_layer:
      inflation_radius: 0.5
      cost_scaling_factor: 1.0
    rolling_window: true
    track_unknown_space: true
    transform_tolerance: 1.0
    subscribe_to_updates: true
    plugins:
    - static_layer
    - inflation_layer
    width: 3
    height: 2
    inflate_unknown: true
    inflate_around_unknown: false
