global_costmap:
  ros__parameters:
    update_frequency: 1.0
    resolution: 0.1
    inflation_layer:
      inflation_radius: 0.5
      cost_scaling_factor: 3.0
    rolling_window: true
    track_unknown_space: true
    transform_tolerance: 0.5
    subscribe_to_updates: false
    plugins:
    - static_layer
    - inflation_layer
    width: 3
    height: 2
    inflate_unknown: true
    inflate_around_unknown: true
