global_costmap:
  ros__parameters:
    update_frequency: 5.0
    resolution: 0.1
    obstacle_layer:
      obstacle_range: 3.0
      raytrace_range: 1.0
    inflation_layer:
      inflation_radius: 0.75
      cost_scaling_factor: 2.0
    rolling_window: true
    track_unknown_space: false
    transform_tolerance: 1.0
    subscribe_to_updates: true
    plugins:
    - static_layer
    - obstacle_layer
    - inflation_layer
    width: 3
    height: 1
    inflate_unknown: false
    inflate_around_unknown: false
