global_costmap:
  ros__parameters:
    update_frequency: 5.0
    resolution: 0.2
    obstacle_layer:
      obstacle_range: 1.0
      raytrace_range: 2.0
    inflation_layer:
      inflation_radius: 0.25
      cost_scaling_factor: 2.0
    rolling_window: true
    track_unknown_space: true
    transform_tolerance: 1.0
    subscribe_to_updates: false
    plugins:
    - static_layer
    - obstacle_layer
    - inflation_layer
    width: 2
    height: 3
    inflate_unknown: true
    inflate_around_unknown: false
