global_costmap:
  ros__parameters:
    update_frequency: 10.0
    resolution: 0.2
    inflation_layer:
      inflation_radius: 0.5
      cost_scaling_factor: 2.0
    rolling_window: false
    track_unknown_space: true
    transform_tolerance: 0.1
    subscribe_to_updates: false
    plugins:
    - static_layer
    - inflation_layer
    inflate_unknown: true
    inflate_around_unknown: false
