version: '3'
services:
  rviz:
    # image: michelalbonico/ros:humble-ros-navigation
    build: .
    container_name: novo_rviz_container
    stdin_open: true               # docker run -i
    tty: true                      # docker run -t
    privileged: true
    restart: unless-stopped
    networks:
      my_custom_network:
        ipv4_address: 172.28.0.101
    
    environment:
    - DISPLAY=${DISPLAY}
    - QT_X11_NO_MITSHM=1
    - XAUTHORITY=/root/.Xauthority
    - TURTLEBOT3_MODEL=waffle
    - ROS_DOMAIN_ID=0
    - RMW_IMPLEMENTATION=rmw_fastrtps_cpp
    - ROS_DISCOVERY_SERVER=172.28.1.1:11811


    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
      - /root/.docker.xauth:/root/.Xauthority:rw
      - /dev:/dev
      - /dev/shm:/dev/shm
      - nav2_data:/data
    
    command: ros2 run rviz2 rviz2 -d /data/nav2_default_view.rviz --ros-args --remap use_sim_time:=True --remap gui:=True
  
volumes:
  nav2_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ${RL4GreenROS_PATH}/docker/data

networks:
  my_custom_network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.28.0.0/16
          gateway: 172.28.0.1