version: '3'
services:
  nav2:
    build: .
    container_name: nav2_container
    stdin_open: true              # docker run -i
    tty: true                      # docker run -t
    privileged: true
    restart: unless-stopped
    networks:
      my_custom_network:
        ipv4_address: 172.28.0.100

    environment:
      - TURTLEBOT3_MODEL=waffle
      - ROS_DOMAIN_ID=0
      - RMW_IMPLEMENTATION=rmw_fastrtps_cpp
      - ROS_DISCOVERY_SERVER=172.28.1.1:11811
      - GAZEBO_MODEL_PATH=$GAZEBO_MODEL_PATH:/opt/ros/humble/share/turtlebot3_gazebo/models

    volumes:
      - /dev:/dev
      - maps:/maps
      - nav2_data:/data
      - nav2_profiler:/profiler
      - exp_orchestration:/orchestrator
      - packages:/packages

    command: ros2 launch nav2_bringup bringup_launch.py use_sim_time:=True map:=/maps/rl4greenros.yaml use_composition:=False
    
volumes:
  nav2_profiler:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ${RL4GreenROS_PATH}/docker/profiler

  nav2_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ${RL4GreenROS_PATH}/docker/data

  exp_orchestration:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ${RL4GreenROS_PATH}/exp-orchestration

  packages:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ${RL4GreenROS_PATH}/workspace/install

  maps:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ${RL4GreenROS_PATH}/docker/maps

networks:
  my_custom_network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.28.0.0/16
          gateway: 172.28.0.1